mysql:
  build: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=mysql
    - MYSQL_DATABASE=loviswpn

mongo:
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - /data/db:/data/db
  command: --smallfiles
